[package]
name = "chipioindustries/gopher"
description = "Grabs the latest Roblox API dump for use in plugins or games"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Llama = "chipioindustries/llama@1.2.2"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"